version: '3.1'
services:
  static:
    container_name: static
    build:
      context: ./server/static_server
    ports:
      - "5000:5000"
    environment: 
      port: 5000
    networks:
      - tea-network
  
  nginx:
    container_name: nginx
    build:
      context: ./server/static_server/nginx
    depends_on:
      - static
    ports:
      - 9080:80
    networks:
      - tea-network
  
  server:
    container_name: server
    build: 
      context: ./server/db_server
    depends_on:
      # - db
      - postgres
    # links:
      # - db
    ports:
      - "8000:8000"
    environment:
      SEQ_DB: playdb
      SEQ_USER: postgres
      SEQ_PW: 0910shc
      DATABASE_URL: postgres://postgres:0910shc@postgres:5432/playdb
      NODE_ENV: development
      PORT: 8000
      # DATABASE_URL: db
      # - DB_HOST=db

  postgres:
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0910shc
      POSTGRES_DB: playdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  tea-network: